export const psychoList = [
  {
    imageUrl: '/img/Psychologist/blank.svg',
    firstName: 'Игорь',
    lastName: 'Батамиров',
    workType: ['Очно', 'Онлайн', 'Переписка'],
    fields: ['Психолог', 'семейный психолог', 'к.п.н'],
    feedbacks: ['первый отзыв', 'второй отзыв'],
    experience: 10,
    age: 35,
    sex: true,
    isMarried: true,
    locations: ['Москва', 'Санкт-Петербург'],
    tags: ['Дети', 'Семья', 'Карьера'],
  },
  {
    imageUrl: '/img/Psychologist/blank.svg',
    firstName: 'Наталья',
    lastName: 'Петрова',
    workType: ['Очно', 'Онлайн'],
    fields: ['Психолог', 'к.п.н'],
    feedbacks: ['первый отзыв', 'второй отзыв'],
    experience: 10,
    age: 35,
    sex: false,
    isMarried: true,
    locations: ['Иркутск'],
    tags: [
      'Дети',
      'Семья',
      'Страхи',
      'Грусть, тоска',
      'Самоопределение',
      'Личностный рост',
    ],
  },
  {
    imageUrl: '/img/Psychologist/blank.svg',
    firstName: 'Элина',
    lastName: 'Кроповницкая',
    workType: ['Онлайн', 'Переписка'],
    fields: ['Психолог', 'семейный психолог', 'к.п.н'],
    feedbacks: ['первый отзыв', 'второй отзыв'],
    experience: 10,
    age: 35,
    sex: false,
    isMarried: false,
    locations: ['Москва', 'Санкт-Петербург'],
    tags: ['Дети', 'Семья', 'Карьера'],
  },
  {
    imageUrl: '/img/Psychologist/blank.svg',
    firstName: 'Любовь',
    lastName: 'Иваненко',
    workType: ['Онлайн', 'Переписка'],
    fields: ['Психолог', 'семейный психолог', 'к.п.н'],
    feedbacks: ['первый отзыв', 'второй отзыв'],
    experience: 10,
    age: 35,
    sex: false,
    isMarried: false,
    locations: ['Москва', 'Санкт-Петербург'],
    tags: ['Дети', 'Семья', 'Карьера'],
  },
  {
    imageUrl: '/img/Psychologist/blank.svg',
    firstName: 'Анна',
    lastName: 'Костина',
    workType: ['Онлайн', 'Переписка'],
    fields: ['Психолог', 'семейный психолог', 'к.п.н'],
    feedbacks: ['первый отзыв', 'второй отзыв'],
    experience: 10,
    age: 35,
    sex: false,
    isMarried: false,
    locations: ['Иркутск'],
    tags: ['Дети', 'Семья', 'Карьера'],
  },
  {
    imageUrl: '/img/Psychologist/blank.svg',
    firstName: 'Леонид',
    lastName: 'Матвеев',
    workType: ['Онлайн', 'Переписка'],
    fields: ['Психолог', 'семейный психолог', 'к.п.н'],
    feedbacks: ['первый отзыв', 'второй отзыв'],
    experience: 10,
    age: 35,
    sex: true,
    isMarried: false,
    locations: ['Иркутск'],
    tags: ['Дети', 'Семья', 'Карьера'],
  },
];
