export const courseList = [
  {
    imgUrl: '/img/pages/main/Courses/blank.png',
    imgHorizontUrl: '/img/pages/main/Courses/blank-horizont.png',
    topics: ['Курс', 'Отношения'],
    head: 'Искусство быть вместе. Большой практический курс о партнёрских отношениях',
    startDate: '15 апреля',
    duralation: 2,
    day: 'По четвергам',
    time: '19:00',
    type: 'Очно',
    address: 'Московский проспект, д.6, БЦ Корона',
    price: 2500,
  },
  {
    imgUrl: '/img/pages/main/Courses/blank.png',
    imgHorizontUrl: '/img/pages/main/Courses/blank-horizont.png',
    topics: ['Курс', 'Отношения'],
    head: 'Искусство быть вместе. Большой практический курс о партнёрских отношениях',
    startDate: '15 апреля',
    duralation: 2,
    day: 'По четвергам',
    time: '19:00',
    type: 'Очно',
    address: 'Московский проспект, д.6, БЦ Корона',
    price: 2500,
  },
  {
    imgUrl: '/img/pages/main/Courses/blank.png',
    imgHorizontUrl: '/img/pages/main/Courses/blank-horizont.png',
    topics: ['Курс', 'Отношения'],
    head: 'Искусство быть вместе. Большой практический курс о партнёрских отношениях',
    startDate: '15 апреля',
    duralation: 2,
    day: 'По четвергам',
    time: '19:00',
    type: 'Очно',
    address: 'Московский проспект, д.6, БЦ Корона',
    price: 2500,
  },
  {
    imgUrl: '/img/pages/main/Courses/blank.png',
    imgHorizontUrl: '/img/pages/main/Courses/blank-horizont.png',
    topics: ['Курс', 'Отношения'],
    head: 'Искусство быть вместе. Большой практический курс о партнёрских отношениях',
    startDate: '15 апреля',
    duralation: 2,
    day: 'По четвергам',
    time: '19:00',
    type: 'Очно',
    address: 'Московский проспект, д.6, БЦ Корона',
    price: 2500,
  },
  {
    imgUrl: '/img/pages/main/Courses/blank.png',
    imgHorizontUrl: '/img/pages/main/Courses/blank-horizont.png',
    topics: ['Курс', 'Отношения'],
    head: 'Искусство быть вместе. Большой практический курс о партнёрских отношениях',
    startDate: '15 апреля',
    duralation: 2,
    day: 'По четвергам',
    time: '19:00',
    type: 'Очно',
    address: 'Московский проспект, д.6, БЦ Корона',
    price: 2500,
  },
];
