export const tariffList = [
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Очно',
    quantity: 1,
    price: 2500,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Очно',
    quantity: 4,
    price: 2500,
    sale: 5,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Очно',
    quantity: 8,
    price: 2500,
    sale: 7,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Очно',
    quantity: 12,
    price: 2500,
    sale: 12,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Онлайн',
    quantity: 1,
    price: 2500,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Онлайн',
    quantity: 4,
    price: 2500,
    sale: 5,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Онлайн',
    quantity: 8,
    price: 2500,
    sale: 7,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Онлайн',
    quantity: 12,
    price: 2500,
    sale: 12,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Переписка',
    quantity: 1,
    price: 2500,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Переписка',
    quantity: 4,
    price: 2500,
    sale: 5,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Переписка',
    quantity: 8,
    price: 2500,
    sale: 7,
    priceOne: 2350,
  },
  {
    personal: '1 на 1',
    tariffPlan: 'Один на один',
    format: 'Переписка',
    quantity: 12,
    price: 2500,
    sale: 12,
    priceOne: 2350,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Очно',
    quantity: 1,
    price: 2500,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Очно',
    quantity: 4,
    price: 2500,
    sale: 5,
    priceOne: 2350,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Очно',
    quantity: 8,
    price: 2500,
    sale: 7,
    priceOne: 2350,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Очно',
    quantity: 12,
    price: 2500,
    sale: 12,
    priceOne: 2350,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Онлайн',
    quantity: 1,
    price: 2500,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Онлайн',
    quantity: 4,
    price: 2500,
    sale: 5,
    priceOne: 2350,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Онлайн',
    quantity: 8,
    price: 2500,
    sale: 7,
    priceOne: 2350,
  },
  {
    personal: 'Семейный',
    tariffPlan: 'Семейный',
    format: 'Онлайн',
    quantity: 12,
    price: 2500,
    sale: 12,
    priceOne: 2350,
  },

  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Очно',
    quantity: 1,
    price: 2500,
  },
  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Очно',
    quantity: 4,
    price: 2500,
    sale: 5,
    priceOne: 2350,
  },
  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Очно',
    quantity: 8,
    price: 2500,
    sale: 7,
    priceOne: 2350,
  },
  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Очно',
    quantity: 12,
    price: 2500,
    sale: 12,
    priceOne: 2350,
  },
  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Онлайн',
    quantity: 1,
    price: 2500,
  },
  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Онлайн',
    quantity: 4,
    price: 2500,
    sale: 5,
    priceOne: 2350,
  },
  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Онлайн',
    quantity: 8,
    price: 2500,
    sale: 7,
    priceOne: 2350,
  },
  {
    personal: 'С ребёнком',
    tariffPlan: 'С ребёнком',
    format: 'Онлайн',
    quantity: 12,
    price: 2500,
    sale: 12,
    priceOne: 2350,
  },
];
