'use client';
import './style/globals.scss';
import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import { Provider } from 'react-redux';
import { store } from '@/store/store';

// const inter = Inter({ subsets: ['latin'] });

// const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   icons: {
//     icon: '/favicon.ico', // /public path
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>
    <>
      <link rel="icon" href="/favicon.ico" />
      <Provider store={store}>
        <Header />
        {children}
        <Footer />
      </Provider>
    </>

    //   </body>
    // </html>
  );
}
