'use client';
import './style/globals.scss';
// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import { Provider } from 'react-redux';
import { store } from '@/store/store';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>
    <>
      <Provider store={store}>
        <Header />
        {children}
        <Footer />
      </Provider>
    </>

    //   </body>
    // </html>
  );
}
